[build]
  base = "packages/frontend"
  command = "yarn install && yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "3.6.4"
  SKIP_PREFLIGHT_CHECK = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
